export class EmailListFakeDb
{
  public static data = [
    {
      'id'    : '5725a680b3249760ea21de52',
      'from'  : 'aaaa@example.com',
      'to': ["bbbb@example.com"],
      'subject': 'This is the first subject',
      'body'  : 'Cutting-edge organizations are using news and data to optimize workflows, support advanced analytics projects, enhance customer engagement and mitigate regulatory risks. ',
      'date': new Date("Sun Feb 7 2021 13:17:00 GMT+0900 (Japan Standard Time)"),
      'attachment': []
    },
    {
      'id'    : '5725a680606588342058356d',
      'from'  : 'bbbb@example.com',
      'to': ["aaaa@example.com"],
      'subject': 'February Valentine',
      'body'  : 'The Dow Jones Developer Platform combines the power of premium content, best-in-class data, deep archives and flexible technology that enables data scientists, developers and UI specialists to design applications and end-to-end solutions that support a range of business objectives.',
      'date': new Date("Mon Feb 8 2021 11:37:00 GMT+0900 (Japan Standard Time)"),
      'attachment': []
    },
    {
      'id'    : '5725a68009e20d0a9e9acf2a',
      'from'  : 'cccc@example.com',
      'to': ["aaaa@example.com", "bbbb@example.com"],
      'subject': 'March Spring',
      'body'  : 'From AI and machine learning initiatives to personalized interfaces and targeted communications, our customers and partners will be able to leverage the full power of trusted news and data in the Dow Jones Developer Platform.',
      'date': new Date("Tue Jan 5 2021 10:01:00 GMT+0900 (Japan Standard Time)"),
      'attachment': ["file.zip"]
    },
    {
      'id'    : '5725a6809fdd915739187ed5',
      'from'  : 'dddd@example.com',
      'to': ["bbbb@example.com", "cccc@example.com"],
      'subject': 'Troy threw the ball to Kevin',
      'body'  : 'Unlock hidden relationships, discover new insights and reliably predict and respond to long-range signals uncovered by text mining, knowledge graphs and dashboards.',
      'date': new Date("Wed Oct 30 2020 10:01:00 GMT+0900 (Japan Standard Time)"),
      'attachment': []
    },
    {
      'id'    : '5725a68007920cf75051da64',
      'from'  : 'eeee@example.com',
      'to': ["dddd@example.com"],
      'subject': 'When will we go to the beach?',
      'body'  : 'Drive innovation and customer engagement by using proprietary and third-party news content and people and company data that leverage open API standards.',
      'date': new Date("Thu Oct 31 2020 10:01:00 GMT+0900 (Japan Standard Time)"),
      'attachment': []
    },
    {
      'id'    : '5725a68031fdbb1db2c1af47',
      'from'  : 'ffff@example.com',
      'to': ["eeee@example.com"],
      'subject': 'Clean your room.',
      'body'  : 'Stay ahead of the competition and fast-paced changes in technology with sales strategies fortified by data and insights from AI tools.',
      'date': new Date("Fri Nov 01 2020 03:01:00 GMT+0900 (Japan Standard Time)"),
      'attachment': []
    },
    {
      'id'    : '5725a680bc670af746c435e2',
      'from'  : 'gggg@example.com',
      'to': ["ffff@example.com"],
      'subject': 'The school is on Elm Street.',
      'body'  : 'Market analysts and data scientists undertake topic modeling and NLP to reveal otherwise unseen trends in competitor behavior and to interpret themes generated by machine learning.',
      'date': new Date("Sun Nov 03 2020 09:17:00 GMT+0900 (Japan Standard Time)"),
      'attachment': ["file.zip"],
    },
    {
      'id'    : '5725a680e7eb988a58ddf303',
      'from'  : 'hhhh@example.com',
      'to': ["gggg@example.com", "dddd@example.com"],
      'subject': 'Ask who or what is doing the action.',
      'body'  : 'Employ longitudinal, machine-readable and licensed data to quickly develop and test trading models.',
      'date': new Date("Mon Nov 04 2020 11:37:00 GMT+0900 (Japan Standard Time)"),
      'attachment': ["file.zip"],
    },
    {
      'id'    : '5725a680dcb077889f758961',
      'from'  : 'iiii@example.com',
      'to': ["eeee@example.com"],
      'subject': 'Who threw the ball?',
      'body'  : 'Conduct sentiment analysis and derive additional insights from news events closely or tangentially related to your target asset class to inform financial strategies.',
      'date': new Date("Tues Nov 05 2020 10:01:00 GMT+0900 (Japan Standard Time)"),
      'attachment': []
    },
    {
      'id'    : '5725a6806acf030f9341e925',
      'from'  : 'jjjj@example.com',
      'to': ["eeee@example.com", "ffff@example.com"],
      'subject': 'My dog always growls at the postal carrier.',
      'body'  : 'Identify event-driven impacts on asset opportunity and risk',
      'date': new Date("Wed Jan 01 2021 18:37:00 GMT+0900 (Japan Standard Time)"),
      'attachment': ["file.zip"],
    },
    {
      'id'    : '5725a680ae1ae9a3c960d487',
      'from'  : 'kkkk@example.com',
      'to': ["iiii@example.com"],
      'subject': 'Basketballs roll across the floor.',
      'body'  : 'M&A signals analysis for advanced predictive models',
      'date': new Date("Thur Jan 02 2021 19:37:00 GMT+0900 (Japan Standard Time)"),
      'attachment': []
    },
    {
      'id'    : '5725a680b8d240c011dd224b',
      'from'  : 'llll@example.com',
      'to': ["jjjj@example.com", "ffff@example.com"],
      'subject': 'I don’t understand the assignment.',
      'body'  : 'Rely on machine learning and longitudinal news data to perform accurate signals analysis and to produce and continuously fuel high-quality predictive models.',
      'date': new Date("Fri Jan 03 2021 15:37:00 GMT+0900 (Japan Standard Time)"),
      'attachment': []
    },
    {
      'id'    : '5725a68034cb3968e1f79eac',
      'from'  : 'mmmm@example.com',
      'to': ["iiii@example.com", "jjjj@example.com"],
      'subject': 'These clothes are too small for me.',
      'body'  : 'News is a proven indicator of adverse events and can help flag emerging risks. Integrated into workflows, news data can generate recommendations, automate decisions and improve screening productivity.',
      'date': new Date("Sat Jan 04 2021 14:07:00 GMT+0900 (Japan Standard Time)"),
      'attachment': []
    },
    {
      'id'    : '5725a6801146cce777df2a08',
      'from'  : 'nnnn@example.com',
      'to': ["iiii@example.com","kkkk@example.com"],
      'subject': 'Peter doesn’t like vegetables.',
      'body'  : 'Seamlessly ingest premium news-derived data to generate unique insights and enhance advanced analytics.',
      'date': new Date("Sun Jan 05 2021 12:33:00 GMT+0900 (Japan Standard Time)"),
      'attachment': ["file.zip"],
    },
    {
      'id'    : '5725a6808a178bfd034d6ecf',
      'from'  : 'oooo@example.comi',
      'to': ["mmmm@example.com", "llll@example.com"],
      'subject': 'Sugar and flour are needed for the recipe.',
      'body'  : 'Consult proprietary news and aggregated third-party content, spanning niche industry publications to global news powerhouses and regional content in 28 languages.',
      'date': new Date("Mon Jan 06 2021 23:37:00 GMT+0900 (Japan Standard Time)"),
      'attachment': ["file.zip"],
    },
    {
      'id'    : '5725a680653c265f5c79b5a9',
      'from'  : 'pppp@example.com',
      'to': ["oooo@example.com"],
      'subject': 'Neither my dad nor my brothers know how to ski.',
      'body'  : 'Access Factivas decades-old archive, licensed with storage rights through contract life, to help you reduce risk, generate accurate data outputs and maintain copyright compliance.',
      'date': new Date("Tue Jan 07 2021 10:37:00 GMT+0900 (Japan Standard Time)"),
      'attachment': []
    },
    {
      'id'    : '5725a680bbcec3cc32a8488a',
      'from'  : 'qqqq@example.com',
      'to': ["pppp@example.com"],
      'subject': 'Pepperoni and cheese are great on a pizza.',
      'body'  : 'Benefit from clean, labeled metadata that include tagged company codes and standardized timestamp formatting across billions of data points.',
      'date': new Date(),
      'attachment': []
    },
    {
      'id'    : '5725a6803d87f1b77e17b62b',
      'from'  : 'rrrr@example.com',
      'to': ["qqqq@example.com", "pppp@example.com"],
      'subject': 'Corned beef and cabbage i',
      'body'  : 'News and data can be tailored to your companys specifications and preferred delivery method, supported by our global solutions engineers at every step.',
      'date': new Date(),
      'attachment': []
    },
    {
      'id'    : '5725a680e87cb319bd9bd673',
      'from'  : 'ssss@example.com',
      'to': ["rrrr@example.com"],
      'subject': 'offline',
      'body'  : 'Increase efficiency with well-structured metadata',
      'date': new Date("Thur Jan 09 2021 22:37:00 GMT+0900 (Japan Standard Time)"),
      'attachment': []
    },
    {
      'id'    : '5725a6802d10e277a0f35775',
      'from'  : 'tttt@example.com',
      'to': ["ssss@example.com", "rrrr@example.com"],
      'subject': 'The creator and producer ',
      'body'  : 'Global and scalable content for data science teams',
      'date': new Date("Fri Jan 10 2021 05:37:00 GMT+0900 (Japan Standard Time)"),
      'attachment': []
    },
    {
      'id'    : '5725a680aef1e5cf26dd3d1f',
      'from'  : 'uuuu@example.compard',
      'to': ["tttt@example.com"],
      'subject': 'My mom or dad is coming to the play',
      'body'  : 'In this sentence, the subject is "Jennifer" and the verb is "walked."',
      'date': new Date("Sat Jan 11 2021 06:37:00 GMT+0900 (Japan Standard Time)"),
      'attachment': []
    },
    {
      'id'    : '5725a680cd7efa56a45aea5d',
      'from'  : 'vvvv@example.com',
      'to': ["uuuu@example.com"],
      'subject': 'Neither gray nor white is my favorite color',
      'body'  : 'In the sentence, the subject is "I" and the verb is "will call."',
      'date': new Date("Sun Jan 12 2021 07:37:00 GMT+0900 (Japan Standard Time)"),
      'attachment': []
    },
    {
      'id'    : '5725a680fb65c91a82cb35e2',
      'from'  : 'wwww@example.com',
      'to': ["ssss@example.com", "vvvv@example.com"],
      'subject': 'Either Grandpa or my sisters are going to the park',
      'body'  : 'Would you like a current or future assignment to be reviewed by the Writing Center? ',
      'date': new Date("Mon Jan 13 2021 08:37:00 GMT+0900 (Japan Standard Time)"),
      'attachment': []
    },
    {
      'id'    : '5725a68018c663044be49cbf',
      'from'  : 'xxxx@example.com',
      'to': ["wwww@example.com", "vvvv@example.com"],
      'subject': 'do-not-disturb',
      'body'  : 'Do you have other general writing questions? Email the Writing Center at ',
      'date': new Date("Tue Jan 14 2021 09:37:00 GMT+0900 (Japan Standard Time)"),
      'attachment': []
    },
    {
      'id'    : '5725a6809413bf8a0a5272b1',
      'from'  : 'yyyy@example.com',
      'to': ["xxxx@example.com"],
      'subject': 'Either my sisters or Grandpa is going to the park.',
      'body'  : 'Other questions about your doctoral capstone or the form and style review? ',
      'date': new Date("Wed Jan 15 2021 10:37:00 GMT+0900 (Japan Standard Time)"),
      'attachment': []
    },
    {
      'id'    : '5725sdff9413bf8a0a5272b1',
      'from'  : 'zzzz@example.com',
      'to': ["yyyy@example.com", "vvvv@example.com"],
      'subject': 'Neither she nor I am going to college. ',
      'body'  : 'Any concerns about accessibility of materials on this site or compatibility with assistive technology',
      'date': new Date("Thur Jan 16 2021 11:37:00 GMT+0900 (Japan Standard Time)"),
      'attachment': []
    }
  ];
}